apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-db-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: movie_db_username
  POSTGRES_PASSWORD: movie_db_password
  POSTGRES_DB: movie_db_{{ .Values.environment }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cast-db-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: cast_db_username
  POSTGRES_PASSWORD: cast_db_password
  POSTGRES_DB: cast_db_{{ .Values.environment }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    upstream movie_service {
        server movie-service:8000;
    }
    
    upstream cast_service {
        server cast-service:8000;
    }
    
    server {
        listen 8080;
        
        location /api/v1/movies {
            proxy_pass http://movie_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /api/v1/casts {
            proxy_pass http://cast_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
