apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
  namespace: {{ .Values.namespace }}
  labels:
    app: movie-db
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: movie-db-config
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: movie-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: movie-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
