environment: staging
namespace: staging

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  nodePort: 30002

movieService:
  replicaCount: 2
  image:
    repository: vn4bit/movie-service
    tag: staging

castService:
  replicaCount: 2
  image:
    repository: vn4bit/cast-service
    tag: staging

nginx:
  replicaCount: 2
  service:
    type: LoadBalancer

ingress:
  host: microservice-staging.local
