environment: dev
namespace: dev

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  nodePort: 30000

movieService:
  replicaCount: 1
  image:
    repository: vn4bit/movie-service
    tag: dev

castService:
  replicaCount: 1
  image:
    repository: vn4bit/cast-service
    tag: dev

nginx:
  replicaCount: 1
  service:
    type: ClusterIP

ingress:
  host: microservice-dev.local
