environment: prod
namespace: prod

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  nodePort: 30003

movieService:
  replicaCount: 3
  image:
    repository: vn4bit/movie-service
    tag: latest

castService:
  replicaCount: 3
  image:
    repository: vn4bit/cast-service
    tag: latest

nginx:
  replicaCount: 3
  service:
    type: LoadBalancer

ingress:
  host: microservice-prod.local

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
