apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
  labels:
    app: cast-service
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.castService.replicaCount }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: "{{ .Values.castService.image.repository }}:{{ .Values.castService.image.tag }}"
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_{{ .Values.environment }}"
        livenessProbe:
          httpGet:
            path: /api/v1/casts/docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/casts/docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-service
  ports:
  - port: 8000
    targetPort: 8000
